name: app
description: App which manages PassKit files.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: 3.22.2

dependencies:
  content_resolver: ^0.3.1
  flutter:
    sdk: flutter
  receive_intent: ^0.2.4
  go_router: ^14.2.0
  passkit: ^0.0.1
  passkit_ui: 
    path: ../passkit_ui
  flutter_localizations:
    sdk: flutter
  intl: any
  drift: ^2.11.1
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.9.0
  google_fonts: ^6.2.1
  flutter_displaymode: ^0.6.0
  file_picker: ^8.0.5

dependency_overrides:
  passkit: 
    path: ../passkit
  passkit_ui: 
    path: ../passkit_ui
  content_resolver:
    git:
      url: git@github.com:espresso3389/flutter_content_resolver.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  drift_dev: ^2.11.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  generate: true