name: app
description: App which manages PassKit files
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.7 <4.0.0'

dependencies:
  content_resolver: ^0.3.0
  flutter:
    sdk: flutter
  receive_intent: ^0.2.4
  go_router: ^10.1.2
  passkit: 
    path: ../passkit
  passkit_ui: 
    path: ../passkit_ui
  flutter_localizations:
    sdk: flutter
  intl: any
  drift: ^2.11.1
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.3
  google_fonts: ^5.1.0
  flutter_displaymode: ^0.6.0
  file_picker: ^5.5.0

dependency_overrides:
  passkit: 
    path: ../passkit
  passkit_ui: 
    path: ../passkit_ui
  content_resolver:
    git:
      url: git@github.com:ueman/flutter_content_resolver.git
      ref: update-gradle

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  drift_dev: ^2.11.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  generate: true