name: passkit_ui
description: A UI kit for PassKit files (usually shown in Apple Wallet). It uses the `passkit` package under the hood.
version: 0.0.5
repository: https://github.com/ueman/passkit
issue_tracker: https://github.com/ueman/passkit/issues
topics:
  - passkit
  - pkpass
  - apple-wallet

screenshots:
  - description: "Screenshot of a PkPass of the boarding pass type"
    path: assets/boarding_pass.webp

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.2"

dependencies:
  barcode: ^2.0.0
  barcode_widget: ^2.0.0
  collection: ^1.18.0
  csslib: ^1.0.0
  flutter:
    sdk: flutter
  meta: any
  passkit: ^0.0.8

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  passkit:
    path: ../passkit
