name: passkit
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/ueman/passkit

environment:
  sdk: ^3.0.7

dependencies:
  archive: ^3.3.5
  barcode: ^2.2.3
  csslib: ^0.17.2
  json_annotation: ^4.7.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  json_serializable: ^6.5.4
